
package dml.team5;

import dml.team5.antlr.PLSQLBaseListener;
import dml.team5.antlr.PLSQLParser;

/**
 * <p>
 * This helper class walks the {@link org.antlr.v4.runtime.tree.ParseTree} to construct the master TABLES {@link java.util.List}.
 * </p>
 * 
 * @author Matthew Boyette (N00868808@ospreys.unf.edu)
 * @version 1.1
 */
public class TableListener extends PLSQLBaseListener
{
    /**
     * <p>
     * Constructs an instance of {@link dml.team5.TableListener}.
     * </p>
     * 
     * @since 1.1
     */
    public TableListener()
    {
        Utility.TABLES.clear();
    }

    /**
     * <p>
     * Adds each table reference seen while walking the {@link org.antlr.v4.runtime.tree.ParseTree} to the master TABLES {@link java.util.List}.
     * </p>
     * 
     * @param ctx
     *            the relevant context generated by the {@link dml.team5.antlr.PLSQLParser} for the 'table_ref' token.
     * @see dml.team5.antlr.PLSQLBaseListener#enterTable_ref(dml.team5.antlr.PLSQLParser.Table_refContext)
     * @since 1.1
     */
    @Override
    public void enterTable_ref(final PLSQLParser.Table_refContext ctx)
    {
        Utility.TABLES.add(ctx.getText().trim());
    }
}
